sonar.projectKey=sjfess_sopra-fs26-group-31-client
sonar.organization=sjfess


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=sopra-fs26-group-31-client
sonar.projectVersion=1.0


# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
